In [9]:
import torch
import numpy as np

In [10]:
torch.__version__

'1.7.0+cpu'

In [11]:
# Check if CUDA is available

torch.cuda.is_available()

False

In [ ]:
# Check current device with CUDA
torch.cuda.current_device()

# Get cuda devices:
torch.cuda.get_device_name(0) # here 0 is id

# Check memory used
torch.cuda.memory_allocated()

In [12]:
lst = [3,4,5,6]
arr = np.array(lst)
arr.dtype

dtype('int64')

In [14]:
arr

array([3, 4, 5, 6])

### Change numpy array to tensor

In [17]:
tensors = torch.from_numpy(arr)
tensors.dtype

torch.int64

In [18]:
tensors

tensor([3, 4, 5, 6])

In [19]:
tensors[1:4]

tensor([4, 5, 6])

In [20]:
tensors.shape

torch.Size([4])

In [21]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [22]:
tensors

tensor([  3,   4,   5, 100])

In [23]:
arr

array([  3,   4,   5, 100])

In [24]:
# To prevent this, use torch.tensor

tensor2 = torch.tensor(arr)


In [25]:
tensor2

tensor([  3,   4,   5, 100])

In [26]:
tensor2[3]=2000

In [27]:
tensor2

tensor([   3,    4,    5, 2000])

In [28]:
arr

array([  3,   4,   5, 100])

In [30]:
## zeros and ones
zero = torch.zeros(2,3,dtype=torch.float64)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [31]:
one = torch.ones(2,3,dtype=torch.float64)
one

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

### Arithematic Operations

In [32]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [33]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [35]:
c=torch.zeros(3)
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [36]:
c

tensor([ 7.,  9., 11.])

In [39]:
### tensor[7,9,11]
torch.add(a,b).sum()

tensor(27.)

### Dot Products and Mult Operations

In [40]:
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [41]:
x.mul(y)

tensor([12., 20., 30.])

In [42]:
x.dot(y)

tensor(62.)

In [43]:
### Matrix multiplication

In [44]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [47]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [48]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [49]:
x@y

tensor([[55., 53.],
        [90., 92.]])