# Back Propogation using Pytorch

In [1]:
import torch
import numpy as np

x^n------------------->derivative wrt x------------>n*(x^n-1)

In [7]:
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [8]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [9]:
### Back propogation y = 2*x
y.backward()

In [10]:
print(x.grad)

tensor(8.)


In [32]:
lst = [[2.,3.,1.], [4.,5.,3.], [7.,6.,4.]]
torch_input=torch.tensor(lst, requires_grad=True)

In [33]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [34]:
# before grad: y=x**3 + x**2
# after grad: y=3*x**2 + 2*x

y = torch_input**3 + torch_input**2

In [35]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [36]:
z = y.sum()

In [37]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [38]:
z.backward()

In [39]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])